### ISSUE TITLE
HttpError 404 when requesting

### ISSUE THREAD

**Issue by workerbcd** [mateuszbaransanok/TrustworthyAI#1]
Hi,

I meet the issue of 404 error when apply **dvc pull**,  could you provide another ways to access the data and the pretrained models?

Thanks

**Comment by mateuszbaransanok** [comment]
Hi, I recently changed the job in which I carried out this project. I also kept data on their drive. Apparently they blocked access to these resources. I have emailed them about this but am still waiting for a response. I'm afraid that data has been lost.

**Comment by mateuszbaransanok** [comment]
Hello, I have great news. The data has been restored and I have uploaded the new configuration to DVC. You can now download all the data you want.
